"""
Django urlpatterns that define the project's API endpoints and their associated views. 

Endpoints:
- Django admin interface: '/admin/'
- Payment API page: '/payments/'
- JWT token obtain endpoint: '/token/'
- JWT token refresh endpoint: '/token/refresh/'
- Menu app endpoints: '/menu/'
- Orders app endpoints: '/orders/'
- Accounts app endpoints: '/users/'
- PermissionGroups endpoint: '/@me/'

Views:
- TokenObtainPairView: View that obtains a JWT token pair for a given user.
- TokenRefreshView: View that refreshes an existing JWT token for a given user.
- PermissionGroups: Viewset that handles CRUD operations for PermissionGroup objects.

Router:
- DefaultRouter: A simple, quick router that generates the endpoints for the PermissionGroups viewset based on the specified basename.
"""

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from .views import PermissionGroups
from rest_framework.routers import DefaultRouter

# Creates a router object
router = DefaultRouter()

# Registers the PermissionGroups viewset class with the endpoint @me
# Basename parameter is used to specify the base name for the url pattern that'll be generated
router.register(r'@me', PermissionGroups, basename="Permissions")


urlpatterns = [
    # Sets up Django admin interface
    path('admin/', admin.site.urls),
    
    # Sets up payment api page
    path('payments/', include('payments.urls')),
    
    # Sets up endpoint for obtaining JWT token
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    
    # Sets up endpoint for refreshing JWT token
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    # Includes url patterns from menu app
    path('menu/', include('menu.urls')),
    
    # Includes url patterns from orders app
    path('orders/', include('orders.urls')),
    
    # Includes url patterns from accounts app
    path('users/', include('accounts.urls')),
    
    # Includes url patterns generated by router
    path('' , include(router.urls)),
]