from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from .views import PermissionGroups
from rest_framework.routers import DefaultRouter

# Creates a router object
router = DefaultRouter()

# Registers the PermissionGroups viewset class with the endpoint @me
# Basename parameter is used to specify the base name for the url pattern that'll be generated
router.register(r'@me', PermissionGroups, basename="Permissions")


urlpatterns = [
    # Sets up Django admin interface
    path('admin/', admin.site.urls),
    
    # Sets up endpoint for obtaining JWT token
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    
    # Sets up endpoint for refreshing JWT token
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    # Includes url patterns from menu app
    path('menu/', include('menu.urls')),
    
    # Includes url patterns from orders app
    path('orders/', include('orders.urls')),
    
    # Includes url patterns from accounts app
    path('users/', include('accounts.urls')),
    
    # Includes url patterns generated by router
    path('' , include(router.urls)),
]